### ISSUE TITLE
URISyntaxException: "Illegal character in opaque part" when trying to run on Windows

### ISSUE THREAD

**Issue by martin-honnen** [xmlcalabash/xmlcalabash3#2]
I am trying to run XML Calabash on Windows but it fails:

```
PS C:\Users\marti\OneDrive\Documents\XMLCalabash\xmlcalabash-3.0.0-alpha1> java -jar xmlcalabash-app-3.0.0-alpha1.jar help
java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\marti\OneDrive\Documents\XMLCalabash\xmlcalabash-3.0.0-alpha1/
```

and

```
PS C:\Users\marti\OneDrive\Documents\XMLCalabash\xmlcalabash-3.0.0-alpha1> java -jar xmlcalabash-app-3.0.0-alpha1.jar run helloWorld.xpl
java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\marti\OneDrive\Documents\XMLCalabash\xmlcalabash-3.0.0-alpha1/
```

Runs fine in a Linux environment (Windows Linux Subsystem).

**Comment by martin-honnen** [comment]
Stacktrace is
```
bash\xmlcalabash-3.0.0-alpha1/
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
        at java.base/java.net.URI$Parser.parse(URI.java:3120)
        at java.base/java.net.URI.<init>(URI.java:600)
        at com.xmlcalabash.util.UriUtils$Companion.dirAsUri(UriUtils.kt:13)
        at com.xmlcalabash.util.UriUtils$Companion.cwdAsUri(UriUtils.kt:8)
        at com.xmlcalabash.app.XmlCalabashCli.loadConfiguration(XmlCalabashCli.kt:197)
        at com.xmlcalabash.app.XmlCalabashCli.run(XmlCalabashCli.kt:62)
        at com.xmlcalabash.app.XmlCalabashCli.access$run(XmlCalabashCli.kt:37)
        at com.xmlcalabash.app.XmlCalabashCli$Companion.run(XmlCalabashCli.kt:41)
        at com.xmlcalabash.app.Main$Companion.main(Main.kt:12)
        at com.xmlcalabash.app.Main.main(Main.kt)
java.net.URISyntaxException: Illegal character in opaque part at index 7: file:C:\Users\marti\OneDrive\Documents\XMLCalabash\xmlcalabash-3.0.0-alpha1/
```

So the error is in https://github.com/xmlcalabash/xmlcalabash3/blob/main/xmlcalabash/src/main/kotlin/com/xmlcalabash/util/UriUtils.kt#L9 doing
```
        fun dirAsUri(dir: String): URI {
            if (dir.endsWith("/")) {
                return URI("file:${dir}")
            } else {
                return URI("file:${dir}/")
            }
        }
```

Perhaps this should use https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#toUri--.

**Comment by ndw** [comment]
Yes. I don't know how pervasive this problem is going to be, but I can see what it is.
